import React from 'react';
import Navbar from '../../Components/Navbar/Navbar';
import Footer from '../../Components/Footer/Footer';

function Stories(props) {
    return (
        <div>
            <Navbar/>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat ac tortor in volutpat. Praesent luctus mi urna, pulvinar vehicula leo feugiat non. In maximus, justo vitae vehicula sodales, nulla risus fringilla turpis, in aliquet tellus ipsum vel lorem. Fusce imperdiet lobortis neque, et ornare eros eleifend quis. Pellentesque id ex eget arcu feugiat sagittis. Sed ut tempus massa. Pellentesque quam est, tincidunt vitae scelerisque ac, gravida ut elit. Nam non iaculis elit. Praesent vitae magna laoreet, commodo urna eu, blandit turpis. Nunc eget orci pretium metus ullamcorper imperdiet. Duis sit amet efficitur lacus, in iaculis magna. Nulla sodales facilisis mi ac suscipit. Mauris varius leo varius risus congue gravida at in diam.</div>
            <br/>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat ac tortor in volutpat. Praesent luctus mi urna, pulvinar vehicula leo feugiat non. In maximus, justo vitae vehicula sodales, nulla risus fringilla turpis, in aliquet tellus ipsum vel lorem. Fusce imperdiet lobortis neque, et ornare eros eleifend quis. Pellentesque id ex eget arcu feugiat sagittis. Sed ut tempus massa. Pellentesque quam est, tincidunt vitae scelerisque ac, gravida ut elit. Nam non iaculis elit. Praesent vitae magna laoreet, commodo urna eu, blandit turpis. Nunc eget orci pretium metus ullamcorper imperdiet. Duis sit amet efficitur lacus, in iaculis magna. Nulla sodales facilisis mi ac suscipit. Mauris varius leo varius risus congue gravida at in diam.</div>
            <br/>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat ac tortor in volutpat. Praesent luctus mi urna, pulvinar vehicula leo feugiat non. In maximus, justo vitae vehicula sodales, nulla risus fringilla turpis, in aliquet tellus ipsum vel lorem. Fusce imperdiet lobortis neque, et ornare eros eleifend quis. Pellentesque id ex eget arcu feugiat sagittis. Sed ut tempus massa. Pellentesque quam est, tincidunt vitae scelerisque ac, gravida ut elit. Nam non iaculis elit. Praesent vitae magna laoreet, commodo urna eu, blandit turpis. Nunc eget orci pretium metus ullamcorper imperdiet. Duis sit amet efficitur lacus, in iaculis magna. Nulla sodales facilisis mi ac suscipit. Mauris varius leo varius risus congue gravida at in diam.</div>
            <br/>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat ac tortor in volutpat. Praesent luctus mi urna, pulvinar vehicula leo feugiat non. In maximus, justo vitae vehicula sodales, nulla risus fringilla turpis, in aliquet tellus ipsum vel lorem. Fusce imperdiet lobortis neque, et ornare eros eleifend quis. Pellentesque id ex eget arcu feugiat sagittis. Sed ut tempus massa. Pellentesque quam est, tincidunt vitae scelerisque ac, gravida ut elit. Nam non iaculis elit. Praesent vitae magna laoreet, commodo urna eu, blandit turpis. Nunc eget orci pretium metus ullamcorper imperdiet. Duis sit amet efficitur lacus, in iaculis magna. Nulla sodales facilisis mi ac suscipit. Mauris varius leo varius risus congue gravida at in diam.</div>
            <br/>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat ac tortor in volutpat. Praesent luctus mi urna, pulvinar vehicula leo feugiat non. In maximus, justo vitae vehicula sodales, nulla risus fringilla turpis, in aliquet tellus ipsum vel lorem. Fusce imperdiet lobortis neque, et ornare eros eleifend quis. Pellentesque id ex eget arcu feugiat sagittis. Sed ut tempus massa. Pellentesque quam est, tincidunt vitae scelerisque ac, gravida ut elit. Nam non iaculis elit. Praesent vitae magna laoreet, commodo urna eu, blandit turpis. Nunc eget orci pretium metus ullamcorper imperdiet. Duis sit amet efficitur lacus, in iaculis magna. Nulla sodales facilisis mi ac suscipit. Mauris varius leo varius risus congue gravida at in diam.</div>
            <br/>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat ac tortor in volutpat. Praesent luctus mi urna, pulvinar vehicula leo feugiat non. In maximus, justo vitae vehicula sodales, nulla risus fringilla turpis, in aliquet tellus ipsum vel lorem. Fusce imperdiet lobortis neque, et ornare eros eleifend quis. Pellentesque id ex eget arcu feugiat sagittis. Sed ut tempus massa. Pellentesque quam est, tincidunt vitae scelerisque ac, gravida ut elit. Nam non iaculis elit. Praesent vitae magna laoreet, commodo urna eu, blandit turpis. Nunc eget orci pretium metus ullamcorper imperdiet. Duis sit amet efficitur lacus, in iaculis magna. Nulla sodales facilisis mi ac suscipit. Mauris varius leo varius risus congue gravida at in diam.</div>
            <br/>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat ac tortor in volutpat. Praesent luctus mi urna, pulvinar vehicula leo feugiat non. In maximus, justo vitae vehicula sodales, nulla risus fringilla turpis, in aliquet tellus ipsum vel lorem. Fusce imperdiet lobortis neque, et ornare eros eleifend quis. Pellentesque id ex eget arcu feugiat sagittis. Sed ut tempus massa. Pellentesque quam est, tincidunt vitae scelerisque ac, gravida ut elit. Nam non iaculis elit. Praesent vitae magna laoreet, commodo urna eu, blandit turpis. Nunc eget orci pretium metus ullamcorper imperdiet. Duis sit amet efficitur lacus, in iaculis magna. Nulla sodales facilisis mi ac suscipit. Mauris varius leo varius risus congue gravida at in diam.</div>
            <br/>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat ac tortor in volutpat. Praesent luctus mi urna, pulvinar vehicula leo feugiat non. In maximus, justo vitae vehicula sodales, nulla risus fringilla turpis, in aliquet tellus ipsum vel lorem. Fusce imperdiet lobortis neque, et ornare eros eleifend quis. Pellentesque id ex eget arcu feugiat sagittis. Sed ut tempus massa. Pellentesque quam est, tincidunt vitae scelerisque ac, gravida ut elit. Nam non iaculis elit. Praesent vitae magna laoreet, commodo urna eu, blandit turpis. Nunc eget orci pretium metus ullamcorper imperdiet. Duis sit amet efficitur lacus, in iaculis magna. Nulla sodales facilisis mi ac suscipit. Mauris varius leo varius risus congue gravida at in diam.</div>
            <br/>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat ac tortor in volutpat. Praesent luctus mi urna, pulvinar vehicula leo feugiat non. In maximus, justo vitae vehicula sodales, nulla risus fringilla turpis, in aliquet tellus ipsum vel lorem. Fusce imperdiet lobortis neque, et ornare eros eleifend quis. Pellentesque id ex eget arcu feugiat sagittis. Sed ut tempus massa. Pellentesque quam est, tincidunt vitae scelerisque ac, gravida ut elit. Nam non iaculis elit. Praesent vitae magna laoreet, commodo urna eu, blandit turpis. Nunc eget orci pretium metus ullamcorper imperdiet. Duis sit amet efficitur lacus, in iaculis magna. Nulla sodales facilisis mi ac suscipit. Mauris varius leo varius risus congue gravida at in diam.</div>
            <br/>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat ac tortor in volutpat. Praesent luctus mi urna, pulvinar vehicula leo feugiat non. In maximus, justo vitae vehicula sodales, nulla risus fringilla turpis, in aliquet tellus ipsum vel lorem. Fusce imperdiet lobortis neque, et ornare eros eleifend quis. Pellentesque id ex eget arcu feugiat sagittis. Sed ut tempus massa. Pellentesque quam est, tincidunt vitae scelerisque ac, gravida ut elit. Nam non iaculis elit. Praesent vitae magna laoreet, commodo urna eu, blandit turpis. Nunc eget orci pretium metus ullamcorper imperdiet. Duis sit amet efficitur lacus, in iaculis magna. Nulla sodales facilisis mi ac suscipit. Mauris varius leo varius risus congue gravida at in diam.</div>
            <br/>
            <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer feugiat ac tortor in volutpat. Praesent luctus mi urna, pulvinar vehicula leo feugiat non. In maximus, justo vitae vehicula sodales, nulla risus fringilla turpis, in aliquet tellus ipsum vel lorem. Fusce imperdiet lobortis neque, et ornare eros eleifend quis. Pellentesque id ex eget arcu feugiat sagittis. Sed ut tempus massa. Pellentesque quam est, tincidunt vitae scelerisque ac, gravida ut elit. Nam non iaculis elit. Praesent vitae magna laoreet, commodo urna eu, blandit turpis. Nunc eget orci pretium metus ullamcorper imperdiet. Duis sit amet efficitur lacus, in iaculis magna. Nulla sodales facilisis mi ac suscipit. Mauris varius leo varius risus congue gravida at in diam.</div>
            <Footer/>
            </div>
    );
}

export default Stories;
